/* eslint-disable prettier/prettier */
export enum AnalyticsEvent {
  SESSION_STARTED = 'SESSION_STARTED',
  SESSION_ENDED = 'SESSION_ENDED',
  CHALLENGE_ATTEMPTED = 'CHALLENGE_ATTEMPTED',
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  SCORE_SUBMITTED = 'SCORE_SUBMITTED',
}
